package com.iarihda.maven.ticketsevice.model;

import java.util.concurrent.atomic.AtomicInteger;

/**
 * A domain class which represents a movie which is showing in the theater. It has the   following fields
 * Movie Id - Autogenerated (acts like a primary key). Starts from 1000.
 * Movie Title – The name of the movie
 * Movie Language – Language in which the movie is played
 * Status (isActive) - A Boolean variable which denotes whether the movie is active at present or not. New show can be created only when the movie is active.
 * @author Adhirai Manickam
 */
public class Movie {

	private int id;
	private String title;
	private String language;
	private boolean isActive;
	
	private static AtomicInteger idGenerator = new AtomicInteger(1000);
	
	/**
	 * Constructor
	 * @param movieId
	 * @param movieName 
	 * @param movieLanguage
	 * @param status
	 */
	public Movie(String movieName, String movieLanguage, boolean status){
		validateParams(movieName,movieLanguage);
		id = idGenerator.getAndIncrement();
		title = movieName;
		language = movieLanguage;
		isActive = status;
	}
	
	/**
	 * Validation for movie name and movie language
	 * @throws IllegalArgumentException
	 */
	private void validateParams(String movieName, String movieLanguage) {
		if(movieName==null || movieLanguage==null)
			throw new IllegalArgumentException("Movie name or language cannot be null");
	}

	/**
	 * @return movie id
	 */
	public int getId() {
		return id;
	}
	
	/**
	 * @return movie name
	 */
	public String getTitle() {
		return title;
	}
	
	/**
	 * @return movie language
	 */
	public String getLanguage() {
		return language;
	}
	
	/**
	 * @return current status of the movie (active or not)
	 */
	public boolean isActive() {
		return isActive;
	}
	
	/**
	 * Used to change the movie name after the object is created.
	 * @param name
	 */
	public void setTitle(String name) {
		validateParams(name, language);
		title = name;
	}
	
	/**
	 * Used to change the language of the movie after the object is created.
	 * @param movieLanguage
	 */
	public void setLanguage(String movieLanguage) {
		validateParams(title, movieLanguage);
		language = movieLanguage;
	}
	
	/**
	 * Change the status of the movie from active to inactive and vice versa
	 */
	public void changeStatus() {
		isActive = !isActive;
	}
	
}
