package com.iarihda.maven.ticketsevice.model;

import java.util.concurrent.atomic.AtomicInteger;

/**
 * A domain class which represents a screen (venue) in the theatre. The members of this class are 
 * Screen Id – Autogenerated (acts like a primary key). Starts from 1000.
 * Screen Name – Another unique identifier to the screen which can be modified by the theatre admin (unlike the screen id).
 * Capacity – No. of seats 
 * Screen Size – The diagonal measurement of the physical screen in inches. This field is used to differentiate IMAX screens from normal ones.
 * Status (isActive) - A Boolean variable which denotes whether the screen is active at present or not. New show can be created (i.e. a movie can be associated with this screen) only when the screen is active.
 * @author Adhirai Manickam
 */
public class Screen {
	
	private int id;
	private String name;
	private int capacity;
	private int size;
	private boolean isActive;
	
	private static AtomicInteger idGenerator = new AtomicInteger(1000);
	
	/**
	 * Constructor
	 * @param name 
	 * @param noOfSeats
	 * @param screenSize
	 * @param status
	 */
	public Screen(String screenName, int noOfSeats,int screenSize,boolean status){
		validateParams(screenName, noOfSeats, screenSize);
		id = idGenerator.getAndIncrement();
		name = screenName;
		capacity = noOfSeats;
		size = screenSize;
		isActive = status;
	}
	
	/**
	 * Validation for screen name, no. of seats, screen size
	 * @throws IllegalArgumentException
	 */
	private void validateParams(String screenName, int noOfSeats, int screenSize) {
		if(screenName==null) 
			throw new IllegalArgumentException("Screen name cannot be null");
		if(noOfSeats<=0 || screenSize<=0 )
			throw new IllegalArgumentException("No. of seats and screen size should be a positive value");
	}
	
	/**
	 * @return the screen id
	 */
	public int getId() {
		return id;
	}

	/**
	 * @return the screen capacity
	 */
	public int getCapacity() {
		return capacity;
	}
	
	/**
	 * @return the screen size
	 */
	public int getSize() {
		return size;
	}
	
	/**
	 * @return screen name
	 */
	public String getName() {
		return name;
	}
	
	/**
	 * @return status (active or not)
	 */
	public boolean isActive() {
		return isActive;
	}
	
	/**
	 * Used to change the no. of seats after the screen object is created.
	 * @param noOfSeats
	 */
	public void setCapacity(int noOfSeats) {
		validateParams(name, noOfSeats, size);
		capacity = noOfSeats;
	}
	
	/**
	 * Used to change the screen name after the screen object is created.
	 * @param newName
	 */
	public void changeName(String newName) {
		validateParams(newName, capacity, size);
		name = newName;
	}
	
	/**
	 * Used to change the size of the screen after the screen object is created.
	 * @param screenSize
	 */
	public void setSize(int screenSize) {
		validateParams(name, screenSize, capacity);
		size = screenSize;
	}
	
	/**
	 * Change the status of the screen from active to inactive and vice versa
	 */
	public void changeStatus() {
		isActive = !isActive;
	}

}
