package com.iarihda.maven.ticketsevice.model;

import java.util.concurrent.atomic.AtomicInteger;

/**
 * A domain class which represents a show (of a movie in a screen at specific time). The member variables are
 * Show Id - Autogenerated (acts like a primary key). Starts from 1000.
 * Movie Id – Id of the movie which is being shown.
 * Screen Id – Id of the screen where the movie is being shown.
 * Show Time – Time of the show
 * Status (isActive) - A Boolean variable which denotes whether the show is active at present or not. A customer can book tickets for a show only when it is active.
 * @author Adhirai Manickam
 */
public class Show {
	
	private int id;
	private Movie movie;
	private Screen screen;
	private String time;
	private boolean isActive;
	
	private static AtomicInteger idGenerator = new AtomicInteger(1000);
	
	/**
	 * Constructor
	 * @param mv_1
	 * @param scrn_1
	 * @param showTime
	 * @param status
	 */
	public Show(Movie mv_1, Screen scrn_1, String showTime, boolean status){
		validateParams(mv_1,scrn_1,showTime);
		id = idGenerator.getAndIncrement();
		movie = mv_1;
		screen = scrn_1;
		time = showTime;
		isActive = status;
	}
	
	/**
	 * Validation for movie, screen and show time
	 * @throws IllegalArgumentException
	 */
	private void validateParams(Movie mv_1, Screen scrn_1, String showTime) {
		if(mv_1==null || scrn_1==null) {
			throw new IllegalArgumentException("Both movie and screen are required to create show.");
		}
		if(!mv_1.isActive()) {
			throw new IllegalArgumentException("Movie is not active. Cannot create show.");
		}
		if(!scrn_1.isActive()) {
			throw new IllegalArgumentException("Screen is not active. Cannot create show.");
		}
		if(showTime==null)
			throw new IllegalArgumentException("Show time cannot be null");
	}

	/**
	 * @return show id
	 */
	public int getId() {
		return id;
	}
	
	/**
	 * @return movie
	 */
	public Movie getMovie() {
		return movie;
	}
	
	/**
	 * @return screen
	 */
	public Screen getScreen() {
		return screen;
	}
	
	/**
	 * @return show time
	 */
	public String  getTime() {
		return time;
	}
	
	public boolean isActive() {
		return isActive;
	}
	
	/**
	 * Used to change the movie after the show is created
	 * @params m
	 */
	public void setMovie(Movie m) {
		validateParams(m, screen, time);
		movie = m;
	}
	
	/**
	 * Used to change the screen after the show is created
	 * @params s
	 */
	public void setScreen(Screen s) {
		validateParams(movie, s, time);
		screen = s;
	}
	
	
	/**
	 * Used to change the show time after the show is created
	 * @params showTime
	 */
	public void setTime(String showTime) {
		validateParams(movie, screen, showTime);
		time = showTime;
	}
	
	
	/**
	 * Used to change the status of the show from active to inactive and vice versa
	 */
	public void changeStatus() {
		isActive = !isActive;
	}
}
